apiVersion: v1
kind: Service
metadata:
  name: taskforge-backend
  namespace: taskforge
spec:
  selector:
    app: taskforge-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000

