apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskforge-ingress
  namespace: taskforge
spec:
  rules:
    - host: taskforge.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskforge-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: taskforge-backend
                port:
                  number: 8000
